name: CI
on:
  pull_request:
env:
  FORCE_COLOR: true
  NODE_VERSION: lts/*
jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/.yarn/unplugged
          key: yarn-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-
      - name: Install Dependencies
        run: yarn install --immutable --inline-builds
        timeout-minutes: 5
      - name: Check code quality
        run: yarn lint:ci
        env:
          FORCE_COLOR: false
      - name: Test application
        run: yarn test
      - name: Install Snyk
        run: npm install --location=global snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Open Source Scanning
        run: snyk test --org=${{ secrets.SNYK_ORG }} --all-projects --sarif-file-output=snyk-oss.sarif
        continue-on-error: true
      - name: Upload results to GitHub Open Source Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-oss.sarif
      - name: Snyk Code Scanning
        run: snyk code test --org=${{ secrets.SNYK_ORG }} --sarif-file-output=snyk-code.sarif
        continue-on-error: true
      - name: Upload results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
